In [5]:
import pandas as pd


In [6]:
df=pd.read_excel(r'F:\project\pycharm_workplace\dissertation_project\analysis\data\result\tmp.xlsx')

In [7]:
df

PN  PD_YEAR  foaming  vessel  resilience  refreshment  \
0    CN109355882-A     2019        0       0           0            0   
1    CN106027776-A     2016        0       0           0            0   
2    CN106125615-A     2016        0       0           0            0   
3  US2015378160-A1     2015        0       0           0            0   

   adjustable neck support  user authentication device  successfully  \
0                        0                           0             0   
1                        0                           0             0   
2                        0                           0             0   
3                        0                           0             0   

   vibration motor  ...  active  stearate  sidewall  uploads  \
0                0  ...       0         0         0        0   
1                0  ...       0         0         0        0   
2                0  ...       0         0         0        0   
3                0  ...       0         0         0        0   

   power connection  rotatably connected  inspiration  user terminals  reader  \
0                 0                    0            0               0       0   
1                 0                    0            0               0       0   
2                 0                    0            0               0       0   
3                 0                    0            0               0       0   

   intelligent riding  
0                   0  
1                   0  
2                   0  
3                   0  

[4 rows x 8058 columns]

In [8]:
import numpy as np

In [14]:
np.where(df!=0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([   0,    1, 2196,    0,    1, 1387,    0,    1, 4490,    0,    1,
        4942], dtype=int64))

In [18]:
iloc=list(zip(np.where(df!=0)[0],np.where(df!=0)[1]))
iloc

[(0, 0),
 (0, 1),
 (0, 2196),
 (1, 0),
 (1, 1),
 (1, 1387),
 (2, 0),
 (2, 1),
 (2, 4490),
 (3, 0),
 (3, 1),
 (3, 4942)]

In [20]:
df.index.values


array([0, 1, 2, 3], dtype=int64)

In [24]:
columns=df.columns.values


In [25]:
columns[2196]

'baffle'

In [26]:
columns[1387]

'experience'

In [27]:
columns[4490]

'state'

In [28]:
columns[4942]

'glass'